export const features = [
  // Non-AI Features
  {
    key: 'programs',
    name: 'Robot Programs',
    description: 'Manage robot arm programs for various manufacturing tasks',
    icon: '🤖',
    color: '#6366f1',
    api: '/programs',
    isAI: false,
    fields: [
      { name: 'name', label: 'Program Name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'type', label: 'Type', type: 'select', options: ['general', 'pick_and_place', 'welding', 'assembly', 'painting', 'inspection', 'palletizing', 'polishing', 'dispensing'] },
      { name: 'status', label: 'Status', type: 'select', options: ['draft', 'active', 'testing', 'archived'] },
      { name: 'created_by', label: 'Created By', type: 'text' },
    ],
    columns: ['name', 'type', 'status', 'created_by'],
  },
  {
    key: 'task-sequences',
    name: 'Task Sequences',
    description: 'Define ordered task sequences for robot operations',
    icon: '📋',
    color: '#3b82f6',
    api: '/task-sequences',
    isAI: false,
    fields: [
      { name: 'name', label: 'Sequence Name', type: 'text', required: true },
      { name: 'priority', label: 'Priority', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['draft', 'active', 'testing', 'archived'] },
      { name: 'steps', label: 'Steps (JSON)', type: 'json' },
    ],
    columns: ['name', 'priority', 'status'],
  },
  {
    key: 'safety-boundaries',
    name: 'Safety Boundaries',
    description: 'Define safety zones and operational limits for robot arms',
    icon: '🛡️',
    color: '#ef4444',
    api: '/safety-boundaries',
    isAI: false,
    fields: [
      { name: 'name', label: 'Zone Name', type: 'text', required: true },
      { name: 'zone_type', label: 'Zone Type', type: 'select', options: ['restricted', 'warning', 'collaborative', 'exclusion', 'reduced_speed'] },
      { name: 'max_speed', label: 'Max Speed (mm/s)', type: 'number' },
      { name: 'max_force', label: 'Max Force (N)', type: 'number' },
      { name: 'is_active', label: 'Active', type: 'boolean' },
      { name: 'coordinates', label: 'Coordinates (JSON)', type: 'json' },
    ],
    columns: ['name', 'zone_type', 'max_speed', 'max_force', 'is_active'],
  },
  {
    key: 'quality-checkpoints',
    name: 'Quality Checkpoints',
    description: 'Configure quality inspection points and criteria',
    icon: '✅',
    color: '#22c55e',
    api: '/quality-checkpoints',
    isAI: false,
    fields: [
      { name: 'name', label: 'Checkpoint Name', type: 'text', required: true },
      { name: 'inspection_type', label: 'Inspection Type', type: 'select', options: ['visual', 'dimensional', 'force', 'torque', 'surface'] },
      { name: 'tolerance', label: 'Tolerance', type: 'number' },
      { name: 'measurement_unit', label: 'Unit', type: 'select', options: ['mm', 'um', 'Nm', 'N', 'degrees'] },
      { name: 'pass_criteria', label: 'Pass Criteria', type: 'text' },
    ],
    columns: ['name', 'inspection_type', 'tolerance', 'measurement_unit'],
  },
  {
    key: 'demonstrations',
    name: 'Demonstration Recordings',
    description: 'Record and manage robot demonstration sessions',
    icon: '🎬',
    color: '#f59e0b',
    api: '/demonstrations',
    isAI: false,
    fields: [
      { name: 'name', label: 'Recording Name', type: 'text', required: true },
      { name: 'duration_seconds', label: 'Duration (seconds)', type: 'number' },
      { name: 'waypoint_count', label: 'Waypoint Count', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['recorded', 'validated', 'processing', 'ready', 'archived'] },
      { name: 'recording_data', label: 'Recording Data (JSON)', type: 'json' },
    ],
    columns: ['name', 'duration_seconds', 'waypoint_count', 'status'],
  },
  {
    key: 'waypoints',
    name: 'Waypoints',
    description: 'Define robot position waypoints with coordinates',
    icon: '📍',
    color: '#06b6d4',
    api: '/waypoints',
    isAI: false,
    fields: [
      { name: 'name', label: 'Waypoint Name', type: 'text', required: true },
      { name: 'x', label: 'X (mm)', type: 'number' },
      { name: 'y', label: 'Y (mm)', type: 'number' },
      { name: 'z', label: 'Z (mm)', type: 'number' },
      { name: 'rx', label: 'Rx (°)', type: 'number' },
      { name: 'ry', label: 'Ry (°)', type: 'number' },
      { name: 'rz', label: 'Rz (°)', type: 'number' },
      { name: 'speed', label: 'Speed (mm/s)', type: 'number' },
    ],
    columns: ['name', 'x', 'y', 'z', 'speed'],
  },
  {
    key: 'tool-configs',
    name: 'Tool Configurations',
    description: 'Configure end-effectors and tool parameters',
    icon: '🔧',
    color: '#8b5cf6',
    api: '/tool-configs',
    isAI: false,
    fields: [
      { name: 'name', label: 'Tool Name', type: 'text', required: true },
      { name: 'tool_type', label: 'Tool Type', type: 'select', options: ['gripper', 'vacuum', 'welding_torch', 'spray_gun', 'screwdriver', 'camera', 'force_sensor', 'deburring'] },
      { name: 'payload_kg', label: 'Payload (kg)', type: 'number' },
      { name: 'grip_force', label: 'Grip Force (N)', type: 'number' },
      { name: 'is_active', label: 'Active', type: 'boolean' },
      { name: 'tcp_offset', label: 'TCP Offset (JSON)', type: 'json' },
    ],
    columns: ['name', 'tool_type', 'payload_kg', 'grip_force', 'is_active'],
  },
  {
    key: 'work-cells',
    name: 'Work Cells',
    description: 'Manage work cell layouts and robot installations',
    icon: '🏭',
    color: '#ec4899',
    api: '/work-cells',
    isAI: false,
    fields: [
      { name: 'name', label: 'Cell Name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'robot_model', label: 'Robot Model', type: 'select', options: ['UR5e', 'UR10e', 'UR16e', 'FANUC CRX-10iA', 'KUKA LBR iiwa', 'ABB YuMi', 'Doosan M1013'] },
      { name: 'max_reach_mm', label: 'Max Reach (mm)', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'maintenance', 'commissioning', 'offline'] },
      { name: 'dimensions', label: 'Dimensions (JSON)', type: 'json' },
    ],
    columns: ['name', 'robot_model', 'max_reach_mm', 'status'],
  },
  // AI Features
  {
    key: 'ai-motion-planning',
    name: 'AI Motion Planning',
    description: 'AI-powered optimal collision-free motion path generation',
    icon: '🧠',
    color: '#8b5cf6',
    api: '/ai-motion-planning',
    isAI: true,
    aiPromptLabel: 'Describe the motion (e.g., "pick from conveyor, avoid obstacle, place on shelf")',
    fields: [
      { name: 'name', label: 'Plan Name', type: 'text', required: true },
      { name: 'start_point', label: 'Start Point (JSON)', type: 'json' },
      { name: 'end_point', label: 'End Point (JSON)', type: 'json' },
      { name: 'constraints', label: 'Constraints (JSON)', type: 'json' },
      { name: 'optimization_score', label: 'Score', type: 'number' },
    ],
    columns: ['name', 'optimization_score'],
    aiFields: ['ai_generated_path'],
  },
  {
    key: 'ai-quality-analysis',
    name: 'AI Quality Analysis',
    description: 'AI-driven quality measurement analysis and recommendations',
    icon: '🔬',
    color: '#3b82f6',
    api: '/ai-quality-analysis',
    isAI: true,
    aiPromptLabel: 'Describe the quality scenario (e.g., "weld bead inspection for automotive frame")',
    fields: [
      { name: 'name', label: 'Analysis Name', type: 'text', required: true },
      { name: 'measurement_data', label: 'Measurement Data (JSON)', type: 'json' },
      { name: 'confidence_score', label: 'Confidence', type: 'number' },
      { name: 'recommendation', label: 'Recommendation', type: 'textarea' },
    ],
    columns: ['name', 'confidence_score', 'recommendation'],
    aiFields: ['ai_analysis'],
  },
  {
    key: 'ai-safety-assessment',
    name: 'AI Safety Assessment',
    description: 'AI-powered safety risk assessment following ISO standards',
    icon: '⚠️',
    color: '#ef4444',
    api: '/ai-safety-assessment',
    isAI: true,
    aiPromptLabel: 'Describe the safety scenario (e.g., "operator working near welding robot")',
    fields: [
      { name: 'name', label: 'Assessment Name', type: 'text', required: true },
      { name: 'scenario_description', label: 'Scenario Description', type: 'textarea' },
      { name: 'risk_level', label: 'Risk Level', type: 'select', options: ['negligible', 'low', 'medium', 'high', 'critical'] },
      { name: 'mitigation_steps', label: 'Mitigation Steps (JSON)', type: 'json' },
    ],
    columns: ['name', 'risk_level', 'scenario_description'],
    aiFields: ['ai_assessment'],
  },
  {
    key: 'ai-task-optimization',
    name: 'AI Task Optimization',
    description: 'AI optimization of robot task sequences for efficiency',
    icon: '⚡',
    color: '#f59e0b',
    api: '/ai-task-optimization',
    isAI: true,
    aiPromptLabel: 'Describe optimization goal (e.g., "reduce cycle time for assembly sequence")',
    fields: [
      { name: 'name', label: 'Optimization Name', type: 'text', required: true },
      { name: 'original_sequence', label: 'Original Sequence (JSON)', type: 'json' },
      { name: 'improvement_percentage', label: 'Improvement %', type: 'number' },
      { name: 'optimization_type', label: 'Type', type: 'select', options: ['time', 'energy', 'quality', 'throughput', 'wear'] },
    ],
    columns: ['name', 'improvement_percentage', 'optimization_type'],
    aiFields: ['ai_optimized_sequence'],
  },
  {
    key: 'ai-anomaly-detection',
    name: 'AI Anomaly Detection',
    description: 'AI-powered detection of anomalies in robot sensor data',
    icon: '📊',
    color: '#06b6d4',
    api: '/ai-anomaly-detection',
    isAI: true,
    aiPromptLabel: 'Describe monitoring scenario (e.g., "joint 3 vibration increase during operation")',
    fields: [
      { name: 'name', label: 'Detection Name', type: 'text', required: true },
      { name: 'sensor_data', label: 'Sensor Data (JSON)', type: 'json' },
      { name: 'severity', label: 'Severity', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
    ],
    columns: ['name', 'severity'],
    aiFields: ['ai_detected_anomalies'],
  },
  {
    key: 'ai-nl-programming',
    name: 'AI Natural Language Programming',
    description: 'Program robot arms using natural language instructions',
    icon: '💬',
    color: '#ec4899',
    api: '/ai-nl-programming',
    isAI: true,
    aiPromptLabel: 'Describe what the robot should do in plain English',
    fields: [
      { name: 'name', label: 'Program Name', type: 'text', required: true },
      { name: 'natural_language_input', label: 'Natural Language Instruction', type: 'textarea' },
      { name: 'ai_generated_code', label: 'Generated Code', type: 'textarea' },
      { name: 'ai_explanation', label: 'Explanation', type: 'textarea' },
    ],
    columns: ['name', 'natural_language_input'],
    aiFields: ['ai_generated_code', 'ai_explanation'],
  },
  {
    key: 'ai-predictive-maintenance',
    name: 'AI Predictive Maintenance',
    description: 'AI prediction of maintenance needs based on sensor data',
    icon: '🔮',
    color: '#22c55e',
    api: '/ai-predictive-maintenance',
    isAI: true,
    aiPromptLabel: 'Describe component to monitor (e.g., "servo motor joint 2 with 5000 hours")',
    fields: [
      { name: 'name', label: 'Record Name', type: 'text', required: true },
      { name: 'component', label: 'Component', type: 'text' },
      { name: 'operational_hours', label: 'Operational Hours', type: 'number' },
      { name: 'next_maintenance_date', label: 'Next Maintenance', type: 'date' },
      { name: 'sensor_readings', label: 'Sensor Readings (JSON)', type: 'json' },
    ],
    columns: ['name', 'component', 'operational_hours', 'next_maintenance_date'],
    aiFields: ['ai_prediction'],
  },
];
